# Generated by Django 5.2.2 on 2025-06-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_room_pin_hashed_alter_room_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='pin_hashed',
        ),
        migrations.AddField(
            model_name='room',
            name='room_pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
